project:
  type: website

website:
  title: "Nicholas Mergendahl"
  description: "Resume of Nicholas Mergendahl."
  navbar:
    title: "Nicholas Mergendahl"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



