---
title: "Nicholas Mergendahl"
---

715-571-1654 | nmergendahl@wisc.edu

## Academic Experience

Basic Neurobiology/Neuroscience

Basic Plant + Animal Biology

Lab Procedures + Experimentation

Coordination w/ Lab Partners

Undergraduate Neuroscience Society Membership @ UW Madison  
Sep. 2023 – May 2024

Research Methods in Psychology  
Fall 2024

## Work Experience

### Paid Tutorship @ UWSP
Jan 2022 – May 2022

- Advised freshman students on introductory chemistry course content

## Volunteer Work

### Wausau Penguin Project
Jun. 13-16

- Assisted attendees, coordination with main production team

### Wausau East High Key Club

- Assistance with organizing local church food pantry
- Serving meals at local church Christmas charity dinner

## Skills

- Data Acquisition/Recording
- Ability to contextualize new information
- Collaboration with a team of individuals with varied roles
- Effective communication w/ team members to accomplish larger tasks
- Experimental Design, collaboration with design team
- Applying new techniques
